USE meubanco;

-- OBS: REMOVENDO O SAFE MODE DO WORKBENCH PARA UPDATE E DELETE QUE NÃO SÃO FEITOS ATRAVÉS DE UMA PK
SET SQL_SAFE_UPDATES = 0; 

-- CRUD
-- CREATE, READ, UPDATE, DELETE

-- CREATE = INSERT -- INSERINDO DADOS NA TABELA
INSERT INTO pessoas (nome, idade, data_nas, profissao) VALUES ('Davi', 20, '2002-03-30', 'programador');
INSERT INTO pessoas (nome, idade, data_nas, profissao) VALUES ('Willis', 19, '2002-09-10', 'montador');

-- READ = SELECT -- LISTANDO OS DADOS DA TABELA
SELECT * FROM pessoas;

-- WHERE -- FILTRANDO VALORES
SELECT * FROM pessoas WHERE idade < 20;

-- UPDATE = UPDATE -- ATUALIZADNO A(s) OS DADOS DA TABELA.
UPDATE pessoas SET idade=21 WHERE nome = 'Davi'; -- IRÁ ATUALIZAR TODOS OS DAVI QUE EXISTIREM NO BANCO. (PROBLEMA GRANDE)

-- DELETE = DELETE -- DELETANDO DADOS DE UMA TABELA

DELETE FROM pessoas WHERE nome='Davi';

